WebForm/Controllers/ChiPhisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebForm
{
    public class ChiPhisController : Controller
    {
        private QuanLyTourEntities db = new QuanLyTourEntities();

        // GET: ChiPhis
        public ActionResult Index()
        {
            var chiPhis = ChiPhi.getAll();
            return View(chiPhis.ToList());
        }

        // GET: ChiPhis/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiPhi chiPhi = ChiPhi.getItemById(id);
            if (chiPhi == null)
            {
                return HttpNotFound();
            }
            return View(chiPhi);
        }

        // GET: ChiPhis/Create
        public ActionResult Create()
        {
            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaDoan");
            ViewBag.MaLoaiChiPhi = new SelectList(db.LoaiChiPhis, "MaLoaiChiPhi", "TenLoaiChiPhi");
            return View();
        }

        // POST: ChiPhis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaChiPhi,MaDoan,SoTien,MaLoaiChiPhi")] ChiPhi chiPhi)
        {
            if (ModelState.IsValid)
            {
                if(ChiPhi.addChiPhi(chiPhi) == 1)
                {
                    return RedirectToAction("Details","DoanDuLiches",new { id = chiPhi.MaDoan.Trim() });
                }
            }

            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaDoan", chiPhi.MaDoan);
            ViewBag.MaLoaiChiPhi = new SelectList(db.LoaiChiPhis, "MaLoaiChiPhi", "TenLoaiChiPhi", chiPhi.MaLoaiChiPhi);
            return View(chiPhi);
        }

        // GET: ChiPhis/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiPhi chiPhi = ChiPhi.getItemById(id);
            if (chiPhi == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaDoan", chiPhi.MaDoan);
            ViewBag.MaLoaiChiPhi = new SelectList(db.LoaiChiPhis, "MaLoaiChiPhi", "TenLoaiChiPhi", chiPhi.MaLoaiChiPhi);
            return View(chiPhi);
        }

        // POST: ChiPhis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaChiPhi,MaDoan,SoTien,MaLoaiChiPhi")] ChiPhi chiPhi)
        {
            if (ModelState.IsValid)
            {
                if(ChiPhi.edit(chiPhi) == 1)
                {
                    return RedirectToAction("Details","DoanDuLiches",new { id = chiPhi.MaDoan.Trim()});

                }
            }
            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaDoan", chiPhi.MaDoan);
            ViewBag.MaLoaiChiPhi = new SelectList(db.LoaiChiPhis, "MaLoaiChiPhi", "TenLoaiChiPhi", chiPhi.MaLoaiChiPhi);
            return View(chiPhi);
        }

        // GET: ChiPhis/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiPhi chiPhi = ChiPhi.getItemById(id);
            if (chiPhi == null)
            {
                return HttpNotFound();
            }
            return View(chiPhi);
        }

        // POST: ChiPhis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            
            if(ChiPhi.delectChiPhi(id) == 1)
            {
                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebForm/Controllers/ChiTietDoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebForm
{
    public class ChiTietDoansController : Controller
    {
        private QuanLyTourEntities db = new QuanLyTourEntities();

        // GET: ChiTietDoans
        public ActionResult Index()
        {
            var chiTietDoans = db.ChiTietDoans.Include(c => c.DoanDuLich).Include(c => c.KhachHang);
            return View(chiTietDoans.ToList());
        }

        // GET: ChiTietDoans/Details/5
        public ActionResult Details(string id,string id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietDoan chiTietDoan = ChiTietDoan.findElementById(id, id2);
            if (chiTietDoan == null)
            {
                return HttpNotFound();
            }
            return View(chiTietDoan);
        }

        // GET: ChiTietDoans/Create
        public ActionResult Create()
        {
            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaDoan");
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoTen");
            return View();
        }

        // POST: ChiTietDoans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDoan,MaKH,Ghichu")] ChiTietDoan chiTietDoan)
        {
            if (ModelState.IsValid)
            {

                if(ChiTietDoan.addChiTietDoan(chiTietDoan) == 1)
                {
                    return RedirectToAction("Details","DoanDuLiches",new { id = chiTietDoan.MaDoan.Trim() });

                }
            }

            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaDoan", chiTietDoan.MaDoan);
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoTen", chiTietDoan.MaKH);
            return View(chiTietDoan);
        }

        // GET: ChiTietDoans/Edit/5
        public ActionResult Edit(string id,string id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietDoan chiTietDoan = ChiTietDoan.findElementById(id, id2);
            if (chiTietDoan == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaDoan", chiTietDoan.MaDoan);
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoTen", chiTietDoan.MaKH);
            return View(chiTietDoan);
        }

        // POST: ChiTietDoans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDoan,MaKH,Ghichu")] ChiTietDoan chiTietDoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chiTietDoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaDoan", chiTietDoan.MaDoan);
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoTen", chiTietDoan.MaKH);
            return View(chiTietDoan);
        }

        // GET: ChiTietDoans/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietDoan chiTietDoan = db.ChiTietDoans.Find(id);
            if (chiTietDoan == null)
            {
                return HttpNotFound();
            }
            return View(chiTietDoan);
        }

        // POST: ChiTietDoans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ChiTietDoan chiTietDoan = db.ChiTietDoans.Find(id);
            db.ChiTietDoans.Remove(chiTietDoan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebForm/Controllers/KhachHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebForm
{
    public class KhachHangsController : Controller
    {
        private QuanLyTourEntities db = new QuanLyTourEntities();

        // GET: KhachHangs
        public ActionResult Index()
        {
            var khachHangs = KhachHang.GetAll();
            return View(khachHangs);
        }

        // GET: KhachHangs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = KhachHang.getKhachHangById(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KhachHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKH,HoTen,SoCMND,DiaChi,GioiTinh,SDT,QuocTich")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                if(KhachHang.addKhachHang(khachHang) == 1)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(khachHang);
        }

        // GET: KhachHangs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = KhachHang.getKhachHangById(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKH,HoTen,SoCMND,DiaChi,GioiTinh,SDT,QuocTich")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                if (KhachHang.edit(khachHang) == 1)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = KhachHang.getKhachHangById(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            KhachHang khachHang = db.KhachHangs.Find(id);
            db.KhachHangs.Remove(khachHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebForm/Views/DoanDuLiches/Create.cshtml
@model WebForm.DoanDuLich

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Đoàn Du Lịch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Mã đoàn</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày khởi hành</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayKhoiHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayKhoiHanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày kết thúc</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tour</label>
            <div class="col-md-10">
                @Html.DropDownList("MaTour", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaTour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebForm/Views/DoanDuLiches/Delete.cshtml
@model WebForm.DoanDuLich

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Đoàn Du Lịch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ngày khởi hành
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayKhoiHanh)
        </dd>

        <dt>
            Ngày kết thúc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayKetThuc)
        </dd>

        <dt>
            Tên gọi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TourDuLich.TenGoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiDungTour.HanhTrinh)
        </dt>

        <dd>
            Hành trình 
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebForm/Views/DoanDuLiches/Details.cshtml
@model WebForm.DoanDuLich

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Đoàn Du Lịch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ngày Khởi Hành
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayKhoiHanh)
        </dd>

        <dt>
            Ngày Kết Thúc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayKetThuc)
        </dd>

        <dt>
            Tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TourDuLich.TenGoi)
        </dd>

        <dt>
            Hành Trình
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDungTour.HanhTrinh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaDoan }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<div>
    <div>
        <h4>Chi Phí</h4>
        <div>@Html.ActionLink("Thêm chi phí", "Create", "ChiPhis")</div>

    </div>
    <table class="table">
        <tr>
            <th>
                Mã Chi Phí
            </th>
            <th>
                Tên Chi Phí
            </th>
            <th>
                Số Tiền
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.ChiPhis)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaChiPhi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoaiChiPhi.TenLoaiChiPhi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoTien)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "ChiPhis",new { id = item.MaChiPhi.Trim() },null) |
                @Html.ActionLink("Details", "Details", "ChiPhis", new { id = item.MaChiPhi.Trim() }, null) |
                @Html.ActionLink("Delete", "Delete", "ChiPhis", new { id = item.MaChiPhi.Trim() }, null)
            </td>
        </tr>
        }
    </table>
</div>


<div>
    <div>
        <h4>Khách Hàng</h4>
        <div>@Html.ActionLink("Thêm khách hàng", "Create", "ChiTietDoans")</div>
    </div>
    <table class="table">
        <tr>
            <th>
                Mã Khách Hàng
            </th>
            <th>
                Họ Tên
            </th>
            <th>
                Giới Tính
            </th>
            <th>
                Số Chứng Minh Nhân Dân
            </th>
            <th>
                Địa Chỉ
            </th>
            <th>
                Số Điện Thoại
            </th>
            <th>
                Quốc Tịch
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.ChiTietDoans)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.HoTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.SoCMND)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.SDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.QuocTich)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "KhachHangs",new { id = item.MaKH.Trim() },null) |
                @Html.ActionLink("Details", "Details", "KhachHangs", new { id = item.MaKH.Trim() },null) |
                @Html.ActionLink("Delete", "Delete", "KhachHangs", new { id = item.MaKH.Trim() }, null)
            </td>
        </tr>
        }
    </table>
</div>

WebForm/Views/DoanDuLiches/Edit.cshtml
@model WebForm.DoanDuLich

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doàn du lịch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDoan)

        <div class="form-group">
            <label class="control-label col-md-2">Ngày khởi hành</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayKhoiHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayKhoiHanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày kết thúc</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mã Tour</label>
            <div class="col-md-10">
                @Html.DropDownList("MaTour", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaTour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebForm/Views/DoanDuLiches/Index.cshtml
@model IEnumerable<WebForm.DoanDuLich>

@{
    ViewBag.Title = "Index";
}

<h2>Đoàn Du Lịch</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Ngày khởi hành
        </th>
        <th>
            Ngày kết thúc
        </th>
        <th>
            Tên gọi
        </th>
        <th>
            Hành Trình
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NgayKhoiHanh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayKetThuc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TourDuLich.TenGoi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoiDungTour.HanhTrinh)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaDoan.Trim() }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaDoan.Trim() }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaDoan.Trim() })
        </td>
    </tr>
}

</table>