WebForm/Controllers/DoanDuLichesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebForm
{
    public class DoanDuLichesController : Controller
    {
        private QuanLyTourEntities db = new QuanLyTourEntities();

        // GET: DoanDuLiches
        public ActionResult Index()
        {
            var doanDuLiches = DoanDuLich.GetAll();
            return View(doanDuLiches.ToList());
        }

        // GET: DoanDuLiches/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DoanDuLich doanDuLich = DoanDuLich.findElementById(id);
            if (doanDuLich == null)
            {
                return HttpNotFound();
            }
            return View(doanDuLich);
        }

        // GET: DoanDuLiches/Create
        public ActionResult Create()
        {
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi");
            ViewBag.MaDoan = new SelectList(db.NoiDungTours, "MaDoan", "HanhTrinh");
            return View();
        }

        // POST: DoanDuLiches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDoan,NgayKhoiHanh,NgayKetThuc,DoanhThu,MaTour")] DoanDuLich doanDuLich)
        {
            if (ModelState.IsValid)
            {
                if(DoanDuLich.addDoanDuLich(doanDuLich) == 1)
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }

            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi", doanDuLich.MaTour);
            ViewBag.MaDoan = new SelectList(db.NoiDungTours, "MaDoan", "HanhTrinh", doanDuLich.MaDoan);
            return View(doanDuLich);
        }

        // GET: DoanDuLiches/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DoanDuLich doanDuLich = DoanDuLich.findElementById(id);
            if (doanDuLich == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi", doanDuLich.MaTour);
            ViewBag.MaDoan = new SelectList(db.NoiDungTours, "MaDoan", "HanhTrinh", doanDuLich.MaDoan);
            return View(doanDuLich);
        }

        // POST: DoanDuLiches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDoan,NgayKhoiHanh,NgayKetThuc,DoanhThu,MaTour")] DoanDuLich doanDuLich)
        {
            if (ModelState.IsValid)
            {
                /*db.Entry(doanDuLich).State = EntityState.Modified;
                db.SaveChanges();*/
                if(DoanDuLich.edit(doanDuLich) == 1)
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi", doanDuLich.MaTour);
            ViewBag.MaDoan = new SelectList(db.NoiDungTours, "MaDoan", "HanhTrinh", doanDuLich.MaDoan);
            return View(doanDuLich);
        }

        // GET: DoanDuLiches/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DoanDuLich doanDuLich = DoanDuLich.findElementById(id);
            if (doanDuLich == null)
            {
                return HttpNotFound();
            }
            return View(doanDuLich);
        }

        // POST: DoanDuLiches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            /*DoanDuLich doanDuLich = db.DoanDuLiches.Find(id);
            db.DoanDuLiches.Remove(doanDuLich);
            db.SaveChanges();*/
            if(DoanDuLich.delete(id) == 1)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebForm/Controllers/GiaToursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebForm
{
    public class GiaToursController : Controller
    {
        private QuanLyTourEntities db = new QuanLyTourEntities();

        // GET: GiaTours
        public ActionResult Index()
        {
            var giaTours = GiaTour.getAll();
            return View(giaTours.ToList());
        }

        // GET: GiaTours/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiaTour giaTour = GiaTour.findElementById(id);
            if (giaTour == null)
            {
                return HttpNotFound();
            }
            return View(giaTour);
        }

        // GET: GiaTours/Create
        public ActionResult Create()
        {
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi");
            return View();
        }

        // POST: GiaTours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaGia,ThoiGianBatDau,ThoiGianKetThuc,ThanhTien,MaTour")] GiaTour giaTour)
        {
            if (ModelState.IsValid)
            {
                if (GiaTour.addGiaTour(giaTour) == 1)
                {
                    return RedirectToAction("Details", "TourDuLiches", new { id = giaTour.MaTour.Trim() });
                }
            }

            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi", giaTour.MaTour);
            return View(giaTour);
        }

        // GET: GiaTours/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiaTour giaTour = GiaTour.findElementById(id);
            if (giaTour == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi", giaTour.MaTour);
            return View(giaTour);
        }

        // POST: GiaTours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaGia,ThoiGianBatDau,ThoiGianKetThuc,ThanhTien,MaTour")] GiaTour giaTour)
        {
            if (ModelState.IsValid)
            {
                if(GiaTour.editGiaTour(giaTour) == 1)
                {
                    return RedirectToAction("Details", "TourDuLiches", new { id = giaTour.MaTour.Trim() });

                }
            }
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi", giaTour.MaTour);
            return View(giaTour);
        }

        // GET: GiaTours/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiaTour giaTour = GiaTour.findElementById(id);
            if (giaTour == null)
            {
                return HttpNotFound();
            }
            return View(giaTour);
        }

        // POST: GiaTours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            
            if(GiaTour.remove(id) == 1)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebForm/Controllers/ThamQuansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebForm
{
    public class ThamQuansController : Controller
    {
        private QuanLyTourEntities db = new QuanLyTourEntities();

        // GET: ThamQuans
        public ActionResult Index()
        {
            var thamQuans = ThamQuan.getAll();
            return View(thamQuans.ToList());
        }

        // GET: ThamQuans/Details/5
        public ActionResult Details(string id, string idDD)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThamQuan thamQuan = ThamQuan.findElementById(id, idDD);
            if (thamQuan == null)
            {
                return HttpNotFound();
            }
            return View(thamQuan);
        }

        // GET: ThamQuans/Create
        public ActionResult Create()
        {
            ViewBag.MaDiaDiem = new SelectList(db.DiaDiems, "MaDiaDiem", "TenDiaDiem");
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi");
            return View();
        }

        // POST: ThamQuans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTour,MaDiaDiem,ThuTu")] ThamQuan thamQuan)
        {
            if (ModelState.IsValid)
            {
                if(ThamQuan.addThamQuan(thamQuan) == 1)
                return RedirectToAction("Details", "TourDuLiches", new { id = thamQuan.MaTour.Trim() });
            }

            ViewBag.MaDiaDiem = new SelectList(db.DiaDiems, "MaDiaDiem", "TenDiaDiem", thamQuan.MaDiaDiem);
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi", thamQuan.MaTour);
            return View(thamQuan);
        }

        // GET: ThamQuans/Edit/5
        public ActionResult Edit(string id,string idDD)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThamQuan thamQuan = ThamQuan.findElementById(id, idDD);
            if (thamQuan == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDiaDiem = new SelectList(db.DiaDiems, "MaDiaDiem", "TenDiaDiem", thamQuan.MaDiaDiem);
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi", thamQuan.MaTour);
            return View(thamQuan);
        }

        // POST: ThamQuans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTour,MaDiaDiem,ThuTu")] ThamQuan thamQuan)
        {
            if (ModelState.IsValid)
            {
                if(ThamQuan.editThamQuan(thamQuan) == 1)
                {
                    return RedirectToAction("Index");
                }
            }
            ViewBag.MaDiaDiem = new SelectList(db.DiaDiems, "MaDiaDiem", "TenDiaDiem", thamQuan.MaDiaDiem);
            ViewBag.MaTour = new SelectList(db.TourDuLiches, "MaTour", "TenGoi", thamQuan.MaTour);
            return View(thamQuan);
        }

        // GET: ThamQuans/Delete/5
        public ActionResult Delete(string id,string idDD)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThamQuan thamQuan = ThamQuan.findElementById(id, idDD);
            if (thamQuan == null)
            {
                return HttpNotFound();
            }
            return View(thamQuan);
        }

        // POST: ThamQuans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id, string idDD)
        {
            if(ThamQuan.deleteThamQuan(id,idDD) == 1)
            {
                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebForm/Views/TourDuLiches/Create.cshtml
@model WebForm.TourDuLich

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tour Du Lịch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Mã Tour</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaTour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaTour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tên Gọi</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenGoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenGoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Đặt Điểm</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DacDiem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DacDiem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mã loại Hình</label>
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiHinh", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiHinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebForm/Views/TourDuLiches/Delete.cshtml
@model WebForm.TourDuLich

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tour Du Lịch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Gọi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenGoi)
        </dd>

        <dt>
            Đặt Điểm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DacDiem)
        </dd>

        <dt>
            Tên Loại Hình
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiHinhDuLich.TenLoaiHinh)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebForm/Views/TourDuLiches/Details.cshtml
@model WebForm.TourDuLich

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tour Du Lich</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Gọi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenGoi)
        </dd>

        <dt>
            Đặc Điểm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DacDiem)
        </dd>

        <dt>
            Loại Hình Du Lịch
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiHinhDuLich.TenLoaiHinh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaTour }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<div>
    <div>
        <h4>Giá Tour</h4>
        <div>@Html.ActionLink("Thêm giá Tour", "Create","GiaTours")</div>
    </div>
    <table class="table">
        <tr>
            <th>
                Mã Giá
            </th>
            <th>
                Thời gian bắt đầu
            </th>
            <th>
                Thời gian kết thúc
            </th>
            <th>
                Giá
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.GiaTours)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaGia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThoiGianBatDau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThoiGianKetThuc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThanhTien)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "GiaTours", new { id = item.MaGia.Trim() }, null) |
                @Html.ActionLink("Details", "Details", "GiaTours", new { id = item.MaGia.Trim() }, null) |
                @Html.ActionLink("Delete", "Delete", "GiaTours", new { id = item.MaGia.Trim() }, null)
            </td>
        </tr>
        }
    </table>
</div>
<div>
    <div>
        <h4>Địa Điểm Tham Quan</h4>
        <div>@Html.ActionLink("Thêm địa điểm tham quan", "Create", "ThamQuans")</div>

    </div>
    <table class="table">
        <tr>
            <th>
                Mã Địa Điểm
            </th>
            <th>
                Tên Địa Điểm
            </th>
            <th>
                Thứ Tự Địa Điểm
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.ThamQuans)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDiaDiem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaDiem.TenDiaDiem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThuTu)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit","ThamQuans", new { id = item.MaTour.Trim(), idDD = item.MaDiaDiem.Trim() },null) |
                @Html.ActionLink("Details", "Details", "ThamQuans", new { id = item.MaTour.Trim(), idDD = item.MaDiaDiem.Trim() },null) |
                @Html.ActionLink("Delete", "Delete", "ThamQuans", new { id = item.MaTour.Trim(), idDD = item.MaDiaDiem.Trim() }, null)
            </td>
        </tr>
        }
    </table>

</div>

<div>
    <div>
        <h4>Các Đoàn Tham Quan</h4>
        <div>@Html.ActionLink("Thêm đoàn du lịch", "Create", "DoanDuLiches")</div>

    </div>
    <table class="table">
        <tr>
            <th>
                Mã Đoàn
            </th>
            <th>
                Ngày Khởi Hành
            </th>
            <th>
                Ngày Kết Thúc
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.DoanDuLiches)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDoan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayKhoiHanh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayKetThuc)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit","DoanDuliches", new { id = item.MaDoan.Trim() },null) |
                @Html.ActionLink("Details", "Details", "DoanDuliches", new { id = item.MaDoan.Trim() }, null) |
                @Html.ActionLink("Delete", "Delete", "DoanDuliches", new { id = item.MaDoan.Trim() }, null)
            </td>
        </tr>
        }
    </table>

</div>

@*
<div>
    <div>
        <h4>Thống Kê</h4>
        <div>@Html.ActionLink("Thêm đoàn du lịch", "Create", "DoanDuLiches")</div>

    </div>
    <table class="table">
        <tr>
            <th>
                Mã Đoàn
            </th>
            <th>
                Doanh Thu
            </th>
            <th>
                Chi Phí
            </th>
            <th>
                Lợi Nhuận
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayKhoiHanh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayKetThuc)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit","DoanDuliches", new { id = item.MaDoan.Trim() },null) |
                @Html.ActionLink("Details", "Details", "DoanDuliches", new { id = item.MaDoan.Trim() }, null) |
                @Html.ActionLink("Delete", "Delete", "DoanDuliches", new { id = item.MaDoan.Trim() }, null)
            </td>
        </tr>
        }
    </table>

</div>*@

WebForm/Views/TourDuLiches/Edit.cshtml
@model WebForm.TourDuLich

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tour Du Lịch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaTour)

        <div class="form-group">
            <label class="control-label col-md-2">Tên Gọi</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenGoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenGoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Đặt Điểm</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DacDiem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DacDiem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mã Loại Hình</label>
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiHinh", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiHinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebForm/Views/TourDuLiches/Index.cshtml
@model IEnumerable<WebForm.TourDuLich>

@{
    ViewBag.Title = "Index";
}

<h2>Tour Du Lịch</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tên Tour
        </th>
        <th>
            Đặt Điểm
        </th>
        <th>
            Tên Loại Hình
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenGoi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DacDiem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiHinhDuLich.TenLoaiHinh)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaTour.Trim() }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaTour.Trim() }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaTour.Trim() })
        </td>
    </tr>
}

</table>