WebForm/Controllers/NhanViensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebForm
{
    public class NhanViensController : Controller
    {
        private QuanLyTourEntities db = new QuanLyTourEntities();

        // GET: NhanViens
        public ActionResult Index()
        {
            var result = NhanVien.GetAll();
            return View(result);
        }

        // GET: NhanViens/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = NhanVien.findElementById(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: NhanViens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NhanViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,TenNV")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                {
                    return RedirectToAction("Index");
                }
            }

            return View(nhanVien);
        }

        // GET: NhanViens/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = NhanVien.findElementById(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: NhanViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,TenNV")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {

                if(NhanVien.edit(nhanVien) == 1)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(nhanVien);
        }

        // GET: NhanViens/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = NhanVien.findElementById(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: NhanViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NhanVien nhanVien = db.NhanViens.Find(id);
            db.NhanViens.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebForm/Controllers/PhanBoNV_DoanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebForm
{
    public class PhanBoNV_DoanController : Controller
    {
        private QuanLyTourEntities db = new QuanLyTourEntities();

        // GET: PhanBoNV_Doan
        public ActionResult Index()
        {
            var phanBoNV_Doan = db.PhanBoNV_Doan.Include(p => p.DoanDuLich).Include(p => p.NhanVien);
            return View(phanBoNV_Doan.ToList());
        }

        // GET: PhanBoNV_Doan/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanBoNV_Doan phanBoNV_Doan = db.PhanBoNV_Doan.Find(id);
            if (phanBoNV_Doan == null)
            {
                return HttpNotFound();
            }
            return View(phanBoNV_Doan);
        }

        // GET: PhanBoNV_Doan/Create
        public ActionResult Create()
        {
            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaDoan");
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TenNV");
            return View();
        }

        // POST: PhanBoNV_Doan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,MaDoan,NhiemVu")] PhanBoNV_Doan phanBoNV_Doan)
        {
            if (ModelState.IsValid)
            {
                db.PhanBoNV_Doan.Add(phanBoNV_Doan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaTour", phanBoNV_Doan.MaDoan);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TenNV", phanBoNV_Doan.MaNV);
            return View(phanBoNV_Doan);
        }

        // GET: PhanBoNV_Doan/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanBoNV_Doan phanBoNV_Doan = db.PhanBoNV_Doan.Find(id);
            if (phanBoNV_Doan == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaTour", phanBoNV_Doan.MaDoan);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TenNV", phanBoNV_Doan.MaNV);
            return View(phanBoNV_Doan);
        }

        // POST: PhanBoNV_Doan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,MaDoan,NhiemVu")] PhanBoNV_Doan phanBoNV_Doan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phanBoNV_Doan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaDoan = new SelectList(db.DoanDuLiches, "MaDoan", "MaTour", phanBoNV_Doan.MaDoan);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "TenNV", phanBoNV_Doan.MaNV);
            return View(phanBoNV_Doan);
        }

        // GET: PhanBoNV_Doan/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanBoNV_Doan phanBoNV_Doan = db.PhanBoNV_Doan.Find(id);
            if (phanBoNV_Doan == null)
            {
                return HttpNotFound();
            }
            return View(phanBoNV_Doan);
        }

        // POST: PhanBoNV_Doan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            PhanBoNV_Doan phanBoNV_Doan = db.PhanBoNV_Doan.Find(id);
            db.PhanBoNV_Doan.Remove(phanBoNV_Doan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebForm/Views/NhanViens/Create.cshtml
@model WebForm.NhanVien

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nhân Viên</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Mã nhân viên</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Tên nhân viên</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebForm/Views/NhanViens/Delete.cshtml
@model WebForm.NhanVien

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebForm/Views/NhanViens/Details.cshtml
@model WebForm.NhanVien

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Nhân viên</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Nhân Viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaNV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<h4>Đoàn Tham Dự</h4>
<div>@Html.ActionLink("Thêm đoàn và chức vụ", "Create", "PhanBoNV_Doan")</div>

<table class="table">
    <tr>
        <th>
            Đoàn Tham Dự
        </th>
        <th>
            Chức Vụ
        </th>
        <th>
            Ngày Khởi Hành
        </th>
        <th>
            Ngày Kết Thúc
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.PhanBoNV_Doan)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDoan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NhiemVu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoanDuLich.NgayKhoiHanh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoanDuLich.NgayKetThuc)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", "doanduliches", new { id = item.MaDoan.Trim() }, null) |
                @Html.ActionLink("Details", "Details", "doanduliches", new { id = item.MaDoan.Trim() }, null) |
                @Html.ActionLink("Delete", "Delete", "doanduliches", new { id = item.MaDoan.Trim() }, null)
            </td>
        </tr>
    }

</table>

WebForm/Views/NhanViens/Edit.cshtml
@model WebForm.NhanVien

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tên nhân viên</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

    <div class="form-group">
        <label class="control-label col-md-2">Tên nhân viên</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebForm/Views/NhanViens/Index.cshtml
@model IEnumerable<WebForm.NhanVien>

@{
    ViewBag.Title = "Index";
}

<h2>Nhân Viên</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tên nhân viên
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenNV)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaNV.Trim() }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaNV.Trim() }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaNV.Trim() })
        </td>
    </tr>
}

</table>